---

resources:
- name: nozzle-release-repo
  type: git
  source:
    branch: ci
    uri: https://github.com/cf-platform-eng/splunk-firehose-nozzle-release.git
    username: cf-platform-eng-machine
    password: {{github-password}}

- name: version
  type: semver
  source:
    driver: s3
    bucket: {{s3-bucket}}
    key: tile-version
    access_key_id: {{s3-access-key}}
    secret_access_key: {{s3-secret}}

- name: splunk-release
  type: s3
  source:
    regexp: releases/cf-splunk.*-(?P<version>.*)\.tgz
    bucket: {{s3-bucket}}
    access_key_id: {{s3-access-key}}
    secret_access_key: {{s3-secret}}

- name: splunk-tile
  type: s3
  source:
    regexp: tiles/splunk.*-(?P<version>.*)\.pivotal
    bucket: {{s3-bucket}}
    access_key_id: {{s3-access-key}}
    secret_access_key: {{s3-secret}}

- name: tile-history
  type: s3
  source:
    regexp: tile-history.yml
    bucket: {{s3-bucket}}
    access_key_id: {{s3-access-key}}
    secret_access_key: {{s3-secret}}


jobs:
- name: unit-tests
  plan:
  - aggregate:
    - get: nozzle-release-repo
      trigger: true
  - task: run-deployment-tests
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: golang
          tag: '1.7'
      inputs:
      - name: nozzle-release-repo
      run:
        path: nozzle-release-repo/ci/unit.sh

- name: build-release
  plan:
  - aggregate:
    - get: nozzle-release-repo
      passed:
        - unit-tests
      trigger: true
    - get: version
  - task: do-build-release
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: guidowb/tile-pipeline
      inputs:
      - name: nozzle-release-repo
      - name: version
      outputs:
        - name: release
      run:
        path: bash
        args:
        - -exc
        - |
          pushd nozzle-release-repo
          ./ci/install.sh
          ./scripts/build-release.sh ../version/number
          popd
          mkdir -p release
          mv nozzle-release-repo/dev_releases/cf-splunk/cf-splunk-*.tgz release
  - put: splunk-release
    params:
      file: release/cf-splunk-*.tgz
  - put: version
    params:
      bump: patch

- name: build-tile
  plan:
  - aggregate:
    - get: nozzle-release-repo
    - get: tile-history
    - get: splunk-release
      passed:
        - build-release
      trigger: true
  - task: do-build-tile
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: guidowb/tile-pipeline
      inputs:
      - name: nozzle-release-repo
      - name: version
      outputs:
        - name: release
      run:
        path: bash
        args:
        - -exc
        - |
          ls -lah
