---

resources:
- name: splunk-tile
  type: s3
  source:
    regexp: tiles/splunk.*-(?P<version>.*)\.pivotal
    bucket: {{s3-bucket}}
    access_key_id: {{s3-access-key}}
    secret_access_key: {{s3-secret}}

- name: missing-properties
  type: s3
  source:
    bucket: {{s3-bucket}}
    versioned_file: splunk-missing-properties.yml
    access_key_id: {{s3-access-key}}
    secret_access_key: {{s3-secret}}

- name: release-repo
  type: git
  source:
    branch: ci
    uri: https://github.com/cf-platform-eng/splunk-firehose-nozzle-release.git
    username: cf-platform-eng-machine
    password: {{github-password}}

- name: tile-generator-repo
  type: git
  source:
    ignore_paths: [ "sample" ]
    branch: master
    uri: http://github.com/cf-platform-eng/tile-generator.git

- name: pcf-environment
  type: pool
  source:
    branch: master
    pool: pcf
    private_key: {{pipeline-resource-pool-github-repo-private-key}}
    uri: git@github.com:cf-platform-eng/pipeline-resource-pool


jobs:
- name: claim-pcf
  plan:
  - aggregate:
    - get: splunk-tile
      trigger: true
    - put: pcf-environment
      params:
        acquire: true

- name: deploy-tile
  plan:
  - aggregate:
    - get: tile-generator-repo
    - get: splunk-tile
    - get: pcf-environment
      passed:
      - claim-pcf
      trigger: true
    - get: release-repo
    - get: missing-properties
  - task: run-deploy-tile
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: guidowb/tile-pipeline
      inputs:
      - name: tile-generator-repo
      - name: pcf-environment
      - name: splunk-tile
      - name: release-repo
      - name: missing-properties
      outputs:
      - name: log
      run:
        path: release-repo/ci/run-deploy-tile.sh
        args:
          - tile-generator-repo
          - release-repo
          - splunk-tile
          - pcf-environment
          - missing-properties
    on_failure:
      aggregate:
        - put: pcf-environment
          params:
            release: pcf-environment

- name: test-deploy
  plan:
  - aggregate:
    - get: tile-generator-repo
    - get: pcf-environment
      passed:
      - deploy-tile
      trigger: true
    - get: release-repo
  - task: run-deployment-tests
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: guidowb/tile-pipeline
      inputs:
      - name: tile-generator-repo
      - name: pcf-environment
      - name: release-repo
      outputs:
      - name: log
      run:
        path: release-repo/ci/run-test-deploy.sh
        args:
          - release-repo
          - pcf-environment
    on_failure:
      aggregate:
        - put: pcf-environment
          params:
            release: pcf-environment

- name: remove-tile
  plan:
  - aggregate:
    - get: tile-generator-repo
    - get: release-repo
    - get: pcf-environment
      passed:
        - test-deploy
      trigger: true
  - task: remove-tile
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: guidowb/tile-pipeline
      inputs:
      - name: tile-generator-repo
      - name: pcf-environment
      - name: release-repo
      outputs:
      - name: log
      run:
        path: release-repo/ci/run-remove-tile.sh
        args:
          - tile-generator-repo
          - pcf-environment
    on_failure:
      aggregate:
        - put: pcf-environment
          params:
            release: pcf-environment

- name: release-pcf
  plan:
  - get: pcf-environment
    passed:
    - remove-tile
    trigger: true
  - put: pcf-environment
    params:
      release: pcf-environment
