---

resources:
- name: nozzle-release-repo
  type: git
  source:
    branch: ci
    uri: https://github.com/cf-platform-eng/splunk-firehose-nozzle-release.git
    username: cf-platform-eng-machine
    password: {{github-password}}

- name: version
  type: semver
  source:
    driver: s3
    bucket: {{s3-bucket}}
    key: tile-version
    access_key_id: {{s3-access-key}}
    secret_access_key: {{s3-secret}}

jobs:
- name: unit-tests
  plan:
  - aggregate:
    - get: nozzle-release-repo
      trigger: true
  - task: run-deployment-tests
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: golang
          tag: '1.7'
      inputs:
      - name: nozzle-release-repo
      run:
        path: nozzle-release-repo/ci/unit.sh

- name: build-tile
  plan:
  - aggregate:
    - get: nozzle-release-repo
      passed:
        - unit-tests
      trigger: true
    - get: version
#  - task: foo
#    config:
#      platform: linux
#      image_resource:
#        type: docker-image
#        source:
#          repository: guidowb/tile-pipeline
#      inputs:
#      - name: nozzle-release-repo
#      - name: version
#      run:
#        path: sh
#        args:
#        - -exc
#        - |
#          ls version
#          echo "version/version"
#          echo ""
#          cat version/version
#          echo "version/number"
#          echo ""
#          cat version/number
  - task: build-release
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: guidowb/tile-pipeline
      inputs:
      - name: nozzle-release-repo
      - name: version
      run:
        dir: nozzle-release-repo
        path: ./scripts/build-release.sh
        args:
          - "../version/number"
